version: 0.9.2-{branch}-{build}

stack: python 3

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Python36"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Python37"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Python38"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Python39"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Python310"
  COVERALLS_REPO_TOKEN:
    secure: 64bL5OipIuqAwg0nGwbra4tIVBheT7jwIKgDuGuV2SefqhwLATu0dSgc/w+ecUE0

init:
  - cmd: set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

build: false

matrix:
  fast_finish: true

install:
  - python -m pip install -U pip
  - python -m pip install .[test]
  - python -m pip install coveralls

test_script:
  - python -m pytest --cov=tesliper --cov-config=.coveragerc test

after_test:
  - coveralls
