# Read the Docs configuration file

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

sphinx:
  builder: html
  configuration: docs/source/conf.py

formats:
  - pdf

python:
  install:
  - method: pip
    path: .
    extra_requirements:
      - gui
      - docs
